spring:
  application:
    name: parcelview
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
server:
  port: ${SERVER_PORT:2320}
  servlet:
    context-path: /api
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

courier:
  ontrac:
    base-url: https://webtrack.ontrac.com
  usps:
    base-url: https://apis.usps.com
    oauth:
      token-url: https://apis.usps.com/oauth2/v3/token
      client-id: ${USPS_CLIENT_ID:}
      client-secret: ${USPS_CLIENT_SECRET:}
  fedex:
    base-url: https://apis.fedex.com
    oauth:
      token-url: https://apis.fedex.com/oauth/token
      client-id: ${FEDEX_CLIENT_ID:}
      client-secret: ${FEDEX_CLIENT_SECRET:}