spring:
  application:
    name: parcelview
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
server:
  port: ${SERVER_PORT:2320}
  servlet:
    context-path: /api
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

courier:
  ontrac:
    base-url: https://webtrack.ontrac.com