CREATE TABLE IF NOT EXISTS TRACKING_INFO (
                                             ID                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                             TRACKING_NUMBER    VARCHAR(255) NOT NULL,
    COURIER            VARCHAR(100) NOT NULL,
    STATUS             VARCHAR(100) NOT NULL,
    STATUS_DETAIL      TEXT,
    ESTIMATED_DELIVERY TIMESTAMP,
    LAST_LOCATION      VARCHAR(255),
    LAST_UPDATED       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS TRACKING_EVENT (
                                              TRACKING_INFO_ID    BIGINT       NOT NULL REFERENCES TRACKING_INFO(ID) ON DELETE CASCADE,
    TRACKING_INFO_KEY   INT          NOT NULL,
    TIMESTAMP           TIMESTAMP    NOT NULL,
    STATUS              VARCHAR(100) NOT NULL,
    DESCRIPTION         TEXT,
    LOCATION            VARCHAR(255)
    );