tasks:
  generateBuildInfo:
    action: !dev.parcelview.buildplugins.generateBuildInfo
      appName: ${pluginSettings.name}
      appVersion: ${pluginSettings.version}
      projectRootDir: ${module.rootDir}
      outputDir: ${taskOutputDir}

generated:
  resources:
    - directory: ${tasks.generateBuildInfo.action.outputDir}